# Generated by Django 4.1.3 on 2023-03-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_classactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classactivity',
            name='week_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='creditclass',
            name='class_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
