# Generated by Django 4.1.3 on 2023-03-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_classactivity_video_id_alter_classactivity_week_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classactivity',
            name='video_id',
        ),
        migrations.AddField(
            model_name='classactivity',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
