# Generated by Django 4.1.3 on 2023-03-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_remove_classactivity_video_id_classactivity_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id']},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='roll_no',
            new_name='student_id',
        ),
    ]
